### ISSUE TITLE
Publish new release for Xcode 7.3 and Swift 2.2

### ISSUE THREAD

**Issue by glennrfisher** [rhodgkins/SwiftHTTPStatusCodes#4]
The `SwiftHTTPStatusCodes` package is breaking projects that depend upon it and use the Carthage dependency manager.

Since the `SwiftHTTPStatusCodes` package includes binary builds with its releases, Carthage downloads the pre-built binary instead of checking out and building the source code. Unfortunately, the most recent release includes a binary that was built with Xcode 7.2, which is not compatible with Xcode 7.3. This produces an error when building a project with Xcode 7.3 that depends upon `SwiftHTTPStatusCodes`: `Module file was created by an older version of the compiler`.

To fix this problem, it would be great if you could publish a new release with a binary built using Xcode 7.3 (or without a pre-built binary at all).

**Comment by rhodgkins** [comment]
Ah yeah I haven't touched it since Xcode 7.3 came out of beta - I'll update tomorrow...!

As a side note - if this happens again (be it with this framework or others) you can just specify the `--no-use-binaries` flag when you run `carthage update` - I won't be changing to not use pre-built binaries as its quicker to download/build them with these.

**Comment by glennrfisher** [comment]
Thanks @rhodgkins! Appreciate the update.

**Comment by rhodgkins** [comment]
@glennrfisher I thought I'd try a lazy option first - I've deleted the attached binaries on the latest release 2.0.2. Do you want to try that - if that fixes your problems I'll go back on what I initially said and leave it as that for now :)

**Comment by glennrfisher** [comment]
Great! Looks like that fixes it. Thanks, @rhodgkins!
